inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

  Exclude:
    - spec/**/*.rb

require:
  - rubocop-performance
  - rubocop-md
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

# Enforcing double quotes reduces the times where you need to switch to Crystal.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true

# Most readable form.
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Exclude:
    - README.md

Lint/InheritException:
  Exclude:
    - lib/r_spec/pending.rb

Naming/PredicateName:
  Exclude:
    - lib/r_spec/expectation_helper.rb

Metrics/ParameterLists:
  Max: 6

Style/ClassAndModuleChildren:
  Exclude:
    - README.md
