language: ruby
sudo: false
cache: bundler
branches:
  only: master
before_install:
  - gem install bundler
script:
  - bundle exec rake test
rvm:
  - 2.6
  - 2.7
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
